name: Formatting (pre-commit)

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - ros2

jobs:
  pre-commit:
    name: Format
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - uses: pre-commit/action@v3.0.0
      id: precommit
    - name: Upload pre-commit changes
      if: failure() && steps.precommit.outcome == 'failure'
      uses: rhaschke/upload-git-patch-action@main
      with:
        name: pre-commit
